version: '3'

services:
  # Backend service
  backend:
    image: demo-mains:latest
    ports:
      - "8000:8000"     
    volumes:
      - ./images:/app/images
    environment:
      PORT: 8000
      DB_HOST: db
      DB_NAME: learnsqlalchemy
      DB_USERNAME: learner
      DB_PASSWORD: StrongPassword123
      REDIS_HOST: redis 

  db: 
    image: postgres:12-alpine 
    environment:
      POSTGRES_USER: learner         
      POSTGRES_PASSWORD: StrongPassword123  
      POSTGRES_DB: learnsqlalchemy
    ports:
      - "5432:5432"
    volumes:
      - ./demodata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data 

volumes:
  demodata:
  redisdata: